name: Continuous Integration

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install Chromium
        run: sudo apt-get install chromium-browser firefox openjdk-8-jdk

      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm install
        name: Install dependencies

      - run: npm run web:git
        name: Running E2E tests
